### PR TITLE
Add skeleton codes for Reminder

### LINKED ISSUE #184: Add skeleton for Reminder

### PR DESCRIPTION
**Pull request by glatiuden**
Changelog
- `Reminder`, `ReminderDate`, `ReminderList` and `ReminderTracker` are created
- Respective CRUD commands and parsers are created as well
- Added Sample Data to facilitate testing of the above classes

Next PR:
- Storage Capability
- Ui

### CODE REVIEW

**Review by jared98lyj — DISMISSED** [review]
LGTM

**Review by Winniehyx — DISMISSED** [review]
LGTM! but sorry there are conflicts now because i changed person to tutor and addressbook to tutorbook :<

**Review by Winniehyx — APPROVED** [review]
LGTM!

**Review by kingsleykuan — APPROVED** [review]
LGTM!

**Pull request merged**
