### PR TITLE
Bug fix for Appointment, Schedule and Reminder

### LINKED ISSUE #241: [PE-D] edit_schedule: cannot edit name
inputting edit_schedule INDEX t/<schedule_name> does not work according to UG, there is no indication of exception handling and a InvocationTargetException and NullPointerException error appears in the command prompt used to open the app

--error message below--

Apr 03, 2021 2:56:12 PM seedu.address.logic.LogicManager execute
INFO: ----------------[USER COMMAND][edit_schedule 3 t/hello]
Exception in thread "JavaFX Application Thread" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1787)
        at javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(FXMLLoader.java:1670)
        at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
        at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
        at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
        at javafx.event.Event.fireEvent(Event.java:198)
        at javafx.scene.Node.fireEvent(Node.java:8879)
        at com.sun.javafx.scene.control.behavior.TextFieldBehavior.fire(TextFieldBehavior.java:184)
        at com.sun.javafx.scene.control.behavior.TextInputControlBehavior.lambda$keyMapping$62(TextInputControlBehavior.java:330)
        at com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
        at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
        at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
        at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
        at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
        at javafx.event.Event.fireEvent(Event.java:198)
        at javafx.scene.Scene$KeyHandler.process(Scene.java:4058)
        at javafx.scene.Scene$KeyHandler.access$1500(Scene.java:4004)
        at javafx.scene.Scene.processKeyEvent(Scene.java:2121)
        at javafx.scene.Scene$ScenePeerListener.keyEvent(Scene.java:2595)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:217)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:149)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleKeyEvent$1(GlassViewEventHandler.java:248)
        at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:390)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleKeyEvent(GlassViewEventHandler.java:247)
        at com.sun.glass.ui.View.handleKeyEvent(View.java:547)
        at com.sun.glass.ui.View.notifyKey(View.java:971)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.reflect.InvocationTargetException
        at jdk.internal.reflect.GeneratedMethodAccessor41.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.sun.javafx.reflect.Trampoline.invoke(MethodUtil.java:76)
        at jdk.internal.reflect.GeneratedMethodAccessor40.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.sun.javafx.reflect.MethodUtil.invoke(MethodUtil.java:273)
        at com.sun.javafx.fxml.MethodHelper.invoke(MethodHelper.java:83)
        at javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1784)
        ... 47 more
Caused by: java.lang.NullPointerException
        at seedu.address.logic.commands.schedulecommands.EditScheduleCommand.execute(EditScheduleCommand.java:138)
        at seedu.address.logic.LogicManager.execute(LogicManager.java:52)
        at seedu.address.ui.MainWindow.executeCommand(MainWindow.java:238)
        at seedu.address.ui.CommandBox.handleCommandEntered(CommandBox.java:45)
        ... 57 more

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: KnitidCeladon23/ped#6

### LINKED ISSUE #248: [PE-D] Adding appointments for past dates
Can add appointments for past dates. Cannot do this for adding schedules which is how I think it is supposed to be for appointments too?

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: vivegank/ped#3

### LINKED ISSUE #250: [PE-D] Multiple appointments at the same time does not show up in timetable
Multiple appointments / schedule at the same time does not show up in timetable. I have 2 appointments and 1 schedule at the same time but only one shows up here. The schedule is blocked by the appointment on top of it I think. This may be related to how clashing appointments can be added

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: vivegank/ped#5

### LINKED ISSUE #273: [PE-D] Edit Schedule
Edit Schedule is buggy.
Unable to press enter when keying t/ or ds/ or fr/ or to/

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: JerardSoh/ped#12

### LINKED ISSUE #274: [PE-D] Edit schedule in UserGuide
I am assuming edit schedule for d/ fr/ and to/ is the same for edit appointment so maybe it should state that all 3 fields should be present as well.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: JerardSoh/ped#13

### LINKED ISSUE #276: [PE-D] Timetable
Timetable covers the Monday.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: JerardSoh/ped#15

### LINKED ISSUE #280: [PE-D] Edit reminder
edit reminder for description field seems to not work

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: JerardSoh/ped#19

### LINKED ISSUE #285: [PE-D] GUI Timetable Overlap
There is an overlap with the Math schedule that obscures part of the Math appointment seen here. This happened when 2 separate events took up a similar slot:

The obscured appointment (index number 2):

The clashing schedule:

Possible remedies that I would like to suggest:
1) Reconfigure GUI to allow both to be displayed at once, similar to how NUSMods shows a timetable clash
2) Update the code to ensure that there are no clashing appointments and schedules

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: yhtMinceraft1010X/ped#5

### PR DESCRIPTION
**Pull request by glatiuden**
Added new `time_from` and `time_to` constraint
1. Earliest time_from: 6:00 AM and latest time_to: 11:00 PM
2. Shortest timeslot: 1 hour and longest timeslot: 8 hours.
3. Timeslot must be in blocks of 30 minutes or 1 hour.
4. Past appointments, schedules and reminders cannot be edited.

Appointment
- Modified the timeslot clashing check to a centralized one under a combined `Event`, to allow checking for overlaps and clashes for both Appointment and Schedule.

Schedule
- Modified the `EditScheduleCommand` to match `EditAppointmentCommand` where all three `date`, `time_from` and `time_to` must be present if any of them are changed.

### CODE REVIEW

**Comment by jared98lyj** [comment]
Wah siccck tks so much!

**Review by jared98lyj — CHANGES_REQUESTED** [review]
Ignore this

**Review by jared98lyj — APPROVED** [review]
LGTM

**Review by Winniehyx — APPROVED** [review]
lgtm

**Pull request merged**
