### PR TITLE
Improved code logic for add_appointment and delete_tutor

### PR DESCRIPTION
**Pull request by jared98lyj**
1. Added checking to ensure that appointment with a tutor that does not exist in the user system will not be successfully added.
2. Also ensured that user cannot delete a tutor who has at least one appointment in the user system.
3. Added methods to ModelManager, AddressBook, AppointmentBook to help check by Name class rather than by Person.
4. This prevents errors when calculating budget or total cost.

### CODE REVIEW

**Review by glatiuden — DISMISSED** [review]
lgtm, take note of the CI error

**Comment by jared98lyj** [comment]
Yup forgot to add new methods to one of the test.

**Review by glatiuden — APPROVED** [review]
LGTM

**Review by kingsleykuan — APPROVED** [review]
LGTM

**Pull request merged**
